name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Build project
      run: |
        npm ci
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/soft-whisper-client
          
          # 코드 업데이트
          git pull origin main
          
          # PM2로 앱 재시작 (없으면 시작)
          pm2 restart soft-whisper || pm2 start "npx serve -s dist -l 3000" --name soft-whisper
          
          # PM2 상태 확인
          pm2 list
          
          echo "✅ Deployment completed!"