name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Build project
        run: |
          npm ci
          npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/soft-whisper-client

            # 기존 프로세스 종료
            pkill -f "serve.*3000" || true

            # 코드 업데이트
            git pull origin main

            # 서버 시작 (빌드는 GitHub에서 이미 완료)
            nohup npx serve -s dist -l 3000 > /dev/null 2>&1 &

            echo "✅ Deployment completed!"
