name: Deploy to EC2 (SSH Only)

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 로컬에서 빌드 (선택사항)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # SSH로 EC2에 접속해서 배포 (PM2 없이)
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 애플리케이션 디렉토리로 이동
            cd /home/ubuntu/your-app-name

            # 기존 프로세스 중지 (포트 기준으로 찾아서 종료)
            sudo lsof -ti:3000 | xargs sudo kill -9 || true

            # 최신 코드 가져오기
            git pull origin main

            # 의존성 설치
            npm ci --production

            # 빌드 (필요한 경우)
            npm run build

            # 백그라운드에서 애플리케이션 시작
            nohup npm start > app.log 2>&1 &

            # 프로세스 확인
            sleep 3
            ps aux | grep node

      # 배포 완료 알림 (선택사항)
      - name: Deployment Status
        run: echo "✅ Deployment completed successfully!"
